### ISSUE TITLE
When call `stopDiscovery`, occur error of M-Search.

### ISSUE THREAD

**Issue by youkinjoh** [futomi/node-upnp-utils#5]
すいません。日本語で。

`startDiscovery`実行後、
まだ`M-Search`のretryが終了していないうちに
`stopDiscovery`をcallした場合、
エラーが発生し落ちてしまいます。

```
var upnpList = [];
setInterval(function() {
  var upnp = require('node-upnp-utils');
  upnp.startDiscovery();
  setTimeout(function() {
    upnp.stopDiscovery(function() {
      upnpList = upnp.getActiveDeviceList();
    });
  },5000);
}, 30000);
```

```
[proj dir]/node_modules/node-upnp-utils/lib/node-upnp-utils.js:476
	sock.send(ssdp, 0, ssdp.length, this.MULTICAST_PORT, this.MULTICAST_ADDR, (err, bytes) => {
	    ^

TypeError: Cannot read property 'send' of null
    at UPnPUtils._sendMsearch ([proj dir]/node_modules/node-upnp-utils/lib/node-upnp-utils.js:476:6)
    at send ([proj dir]/node_modules/node-upnp-utils/lib/node-upnp-utils.js:345:8)
    at Timeout.msearch_timer_id.setTimeout [as _onTimeout] ([proj dir]/node_modules/node-upnp-utils/lib/node-upnp-utils.js:349:11)
    at tryOnTimeout (timers.js:228:11)
    at Timer.listOnTimeout (timers.js:202:5)
exit 1
```

`M-Search`のretryのためにここの`send`が繰り返し実行されています。
https://github.com/futomi/node-upnp-utils/blob/35fbccb1ccdea088d3ca62e174ae9f818bb22f9b/lib/node-upnp-utils.js#L344

`send`の中でさらにcallしている`_sendMsearch`では、
`unicast`を取得し次の行で`send`をcallしています。
https://github.com/futomi/node-upnp-utils/blob/35fbccb1ccdea088d3ca62e174ae9f818bb22f9b/lib/node-upnp-utils.js#L475

`stopDiscovery`実行時には
`multicast`と`unicast`のcloseと削除(正確には`null`を代入)が行われています。
https://github.com/futomi/node-upnp-utils/blob/35fbccb1ccdea088d3ca62e174ae9f818bb22f9b/lib/node-upnp-utils.js#L574

この場合でも、`_sendMsearch`は繰り返しcallされているため、
`null`となっている`unicast`を取得し`send`をcallしてエラーとなっています。

`this.discovery_started`を見て処理にガードするのが良さそうですが、
`_startMsearch`内の`send`で行うべきか
`_sendMsearch`内で処理すべきか判断がつかなかったため
`pull request`せずに`issue`に登録します。

**Comment by youkinjoh** [comment]
多分原因がわかりました。
node.js上のtimer系の挙動が変更されているのが原因のようです。
`setTimeout`や`setInterval`は以前はブラウザと同じように数値を返していましたが
現在のnode.jsでは`Timeout`オブジェクトを返しているようです。

```
console.log(setTimeout(function() {}, 0).constructor); //=> [Function: Timeout]
console.log(setInterval(function() {}, 0).constructor);  //=> [Function: Timeout]
```
